# Load wallpapers into memory
preload = /home/diller/Downloads/wallpapersden.com_black-hole-hd-digital_3840x1620.jpg

# Laptop screen
wallpaper = eDP-1,/home/diller/Downloads/wallpapersden.com_black-hole-hd-digital_3840x1620.jpg

# External monitor
wallpaper = HDMI-A-5,/home/diller/Downloads/wallpapersden.com_black-hole-hd-digital_3840x1620.jpg
