# Load wallpapers into memory
preload = /home/diller/Downloads/5748285.jpg

# Laptop screen
wallpaper = eDP-1,/home/diller/Downloads/5748285.jpg

# External monitor
wallpaper = HDMI-A-5,/home/diller/Downloads/5748285.jpg
